# Generated by Django 4.2.4 on 2023-10-06 04:15

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('free_pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipBenefits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefits', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
