# Generated by Django 4.2.4 on 2023-10-09 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('free_pages', '0004_alter_post_main_category_alter_subcategory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='free_pages.subcategory'),
        ),
    ]
