# Generated by Django 4.2.4 on 2023-10-08 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('free_pages', '0002_membershipbenefits'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='main_category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='free_pages.maincategory'),
            preserve_default=False,
        ),
    ]
