# Generated by Django 4.2.4 on 2023-10-08 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('free_pages', '0003_post_main_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='main_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='free_pages.maincategory'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='free_pages.maincategory'),
        ),
    ]
