from playwright.sync_api import Page, expect

def test_create_subscriber(page: Page, django_admin_credentials, domain) -> None:
    admin_user, admin_password = django_admin_credentials
    page.goto(domain)
    page.get_by_role("link", name="Become a Member").click()
    page.get_by_role("link", name="Subscribe").nth(1).click()
    page.get_by_role("link", name="Sign Up").click()
    page.get_by_placeholder("Username").click()
    page.get_by_placeholder("Username").fill("test_member")
    page.get_by_placeholder("Email").click()
    page.get_by_placeholder("Email").fill("test@test.com")
    page.get_by_placeholder("Password", exact=True).click()
    page.get_by_placeholder("Password", exact=True).fill("123test123")
    page.get_by_placeholder("Confirm Password").click()
    page.get_by_placeholder("Confirm Password").fill("123test123")
    page.get_by_role("button", name="Sign Up").click()    
    page.get_by_role("link", name="Subscribe").nth(1).click()
    page.get_by_label("Email").click()
    page.get_by_label("Email").fill("tst@test.com")
    page.get_by_placeholder("1234 1234 1234 1234").click()
    page.get_by_placeholder("1234 1234 1234 1234").fill("4242 4242 4242 4242")
    page.get_by_placeholder("MM / YY").click()
    page.get_by_placeholder("MM / YY").fill("01 / 34")
    page.get_by_placeholder("CVC").click()
    page.get_by_placeholder("CVC").fill("233")
    page.get_by_placeholder("Full name on card").click()
    page.get_by_placeholder("Full name on card").fill("tester")
    page.get_by_test_id("hosted-payment-submit-button").click()
    page.goto(f"{domain}/admin/login/?next=/admin/")
    page.get_by_label("Username:").click()
    page.get_by_label("Username:").fill(admin_user)
    page.get_by_label("Username:").press("Tab")
    page.get_by_label("Password:").click()
    page.get_by_label("Password:").fill(admin_password)
    page.get_by_role("button", name="Log in").click()
    page.get_by_role("link", name="Users").click()
    page.get_by_role("row", name="test_member").get_by_role("checkbox").check()
    page.get_by_label("Action: \n  ---------\n\n  Delete selected users").select_option("delete_selected")
    page.get_by_role("button", name="Go").click()
    page.get_by_role("button", name="Yes, I’m sure").click()
    page.close()
